let jobData = [
  {
    id: 1,
    postion: "Full Stack Developer",
    postedOn: "2024-10-12",
    skill: ["Node", "Javascript", "Mongo", "Express"],
    experince: 5,
    company: "Amazon",
    location: "Remote",
    type: "Full Time",
    jobLink: "https://amazon.jobs/en/",
  },
  {
    id: 2,
    postion: "Frontend Developer",
    postedOn: "2024-11-12",
    skill: ["Node", "Javascript", "React", "CSS"],
    experince: 5,
    company: "Apple",
    location: "In-offce",
    type: "Part Time",
    jobLink: "https://amazon.jobs/en/",
  },
  {
    id: 3,
    postion: "Backend Developer",
    postedOn: "2024-12-12",
    skill: ["Node", "Javascript", "MongoDB"],
    experince: 2,
    company: "Google",
    location: "hybird",
    type: "Freelance",
    jobLink: "https://amazon.jobs/en/",
  },
  {
    id: 5,
    postion: "Full Stack Developer",
    postedOn: "2024-03-12",
    skill: ["C++", "NoSQL", "JAVA"],
    experince: "Fresher",
    company: "Microsoft",
    location: "In-office",
    type: "Full Time",
    jobLink: "https://amazon.jobs/en/",
  },
  {
    id: 6,
    postion: "Frontend Developer",
    postedOn: "2024-10-23",
    skill: ["Node", "Javascript", "HTML5", "C#"],
    experince: 5,
    company: "Amazon",
    location: "Remote",
    type: "Part Time",
    jobLink: "https://amazon.jobs/en/",
  },
];

export default jobData;
